language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer self-update
  - composer require orchestra/testbench:"$TESTBENCH_VERSION" illuminate/support:"$LARAVEL_VERSION"
  - composer install
  - which phpunit
  - phpunit --version

script: phpunit --coverage-text
